# Generated by Django 4.2.6 on 2023-11-14 06:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbmain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollmentDate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Enrollment',
            },
        ),
        migrations.RenameField(
            model_name='classschedule',
            old_name='fk_nstructor',
            new_name='fk_instructor',
        ),
        migrations.RemoveField(
            model_name='content',
            name='totalViews',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='verificationStatus',
        ),
        migrations.RemoveField(
            model_name='quizes',
            name='endDate',
        ),
        migrations.RemoveField(
            model_name='quizes',
            name='fk_quizQAndAID',
        ),
        migrations.RemoveField(
            model_name='quizes',
            name='maxScore',
        ),
        migrations.RemoveField(
            model_name='quizes',
            name='startDate',
        ),
        migrations.RemoveField(
            model_name='quizes',
            name='time',
        ),
        migrations.RemoveField(
            model_name='quizes',
            name='userScore',
        ),
        migrations.AddField(
            model_name='content',
            name='content_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='video',
            field=models.FileField(blank=True, default=1, null=True, upload_to='video'),
        ),
        migrations.AddField(
            model_name='course',
            name='fk_student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dbmain.student', verbose_name='Student'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='profilePicture',
            field=models.ImageField(blank=True, null=True, upload_to='teacher_images/'),
        ),
        migrations.AddField(
            model_name='material',
            name='file',
            field=models.FileField(blank=True, default=1, null=True, upload_to='file'),
        ),
        migrations.AddField(
            model_name='quizes',
            name='fk_student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dbmain.student', verbose_name='Student'),
        ),
        migrations.AddField(
            model_name='quizes',
            name='quiz_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='profilePicture',
            field=models.ImageField(blank=True, null=True, upload_to='student_images/'),
        ),
        migrations.AlterField(
            model_name='content',
            name='contentTitle',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='fk_syllabus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmain.syllabus', verbose_name='Syllabus'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='contactNumber',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='dob',
            field=models.DateField(default=datetime.date(2000, 1, 1)),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='email',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='firstName',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='lastName',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='password',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='contactNumber',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.DateField(default=datetime.date(2000, 1, 1)),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='firstName',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='lastName',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='verificationStatus',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='chapters',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Enrollments',
        ),
        migrations.DeleteModel(
            name='QuizQAndA',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='fk_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_courses', to='dbmain.course', verbose_name='Course'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='fk_student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_student', to='dbmain.student', verbose_name='Student'),
        ),
    ]
